docs: Update CANalyst-II interface describe (#179)
UAVCAN/pyuavcan pull request #180
Opened 2021-09-03 13:38 UTC by Cherish-Gww

2021-09-03 13:47 UTC, pavel-kirienko requested changes
Please bump the patch version number in `pyuavcan/VERSION`.

2021-09-03 13:47 UTC, pavel-kirienko commented on pyuavcan/transport/can/media/pythoncan/_pythoncan.py
> +              ``pip3 install git+https://github.com/Cherish-Gww/python-can.git@add_canalystii_so``
```suggestion
              ``pip3 install git+https://github.com/Cherish-Gww/python-can.git@add_canalystii_so``
              More info: https://github.com/UAVCAN/pyuavcan/issues/178#issuecomment-912497882
```

2021-09-06 16:21 UTC, pavel-kirienko approved these changes
Looks good except for one missing preposition in "you need download". Should I merge this?

In the future, feel free to explicitly request a review when done using the button in the upper-right side of the page.

2021-09-07 07:11 UTC, Cherish-Gww commented
@pavel-kirienko 
Thank you very much, I have changed annotation, forgive my poor English.
and Is there uavcan organization have a online chat to discuss issues?

2021-09-07 08:10 UTC, merged